### ISSUE TITLE
Easy way to "scroll" through breakpoints

### ISSUE THREAD

**Issue by mmagdon** [sigatrev/Rhythm-Horizon-Issue-Tracker#12]

**Comment by sigatrev** [comment]
I've implemented a few things in the next release, ctrl + shift + comma/period will jump to the prev/next timing elements. If you're editting a timing change or breakpoint( right click + edit <thing> ) it will jump to the next element, if you're browsing normally it will move the prompt to the next point, always moving at least as far as the next "snap" to ensure you won't get "stuck" in a place.

If you open the TimingData Window ( right click + view timing data ), you can double click on a breakpoint or timing change from the lists to jump to that element.
