### ISSUE TITLE
Sorting the search menu

### ISSUE THREAD

**Issue by mmagdon** [sigatrev/Rhythm-Horizon-Issue-Tracker#3]
When searching for songs or charts, the top fields should be able to be clicked on to sort by either alphabetically (for fields like Songs and Artist) or numerically (for fields like Charts, BPM, and Length)

**Comment by sigatrev** [comment]
Added in v0.0.2.5. I have some UI cleanup to do to make it clear how it is sorted if it is, and which fields can be used for sorting( i.e. not Graph, Graphics, etc ), but this is a start.
