### ISSUE TITLE
Sort content management screen

### ISSUE THREAD

**Issue by mmagdon** [sigatrev/Rhythm-Horizon-Issue-Tracker#8]

**Comment by sigatrev** [comment]
Assuming this means the same thing as issue #3, this is implemented in v0.0.2.5. If this is means something else, re-open the issue and provide more information.

**Comment by mmagdon** [comment]
Sorry for the ambiguity. This was separate than issue #3. Issue #3 was in regards to sorting the Search Menu, but this is in regards to sorting the base Content Management screen (where packs are, Unsorted Charts, Uncharted Songs, etc.). If this was implemented beforehand or in v0.0.2.5, feel free to close the issue again, but I hope this clears it up.

**Comment by mmagdon** [comment]
@sigatrev  apparently you're the only one that can reopen the issue, as I can only reopen issues if I'm the one who closed it

source: https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github

**Comment by sigatrev** [comment]
Different menu, but same functionality, correct?

**Comment by mmagdon** [comment]
I will have to download v0.0.2.5 tonight to confirm, but yes, same functionality. Any screen that lists songs, charts, etc., that has columns + a header (like the Search menu and the Content Management screen) should have a clickable header to sort it by that category.

**Comment by sigatrev** [comment]
Ok, "same functionality" was what I meant by "Assuming this means the same thing as issue #3". I implemented the functionality for both the normal Content Browser and the Search Window's browser. I still need to make the UI a little better( they don't highlight when you hover over them, there is no indication which is currently being used to sort, etc ), but it is there now.
