### ISSUE TITLE
Add indication to content management screen if a song is not uploaded

### ISSUE THREAD

**Issue by mmagdon** [sigatrev/Rhythm-Horizon-Issue-Tracker#9]

**Comment by sigatrev** [comment]
The following is changes are included in the next release( 0.0.2.6 )

Any time you do a search for content on the server, it will remember what it saw and know that it is on the server in the future.

When you upload a song, if it reaches the point that it says "Success" on the status display on your system should mark it as "online". If you close the game before hand it reaches that point, or there are any problems processing that are later resolved, your system won't know until you see it in a search.

If the chart or songs fails to upload with a specific failure reason, a check will be made to see if that chart or song is already on the server, and your system will mark it as such.

Note that currently, the online status marking won't update until you refresh the content browser display, regardless of which way the system is informed that a piece of content is or is not on the server.
